name = "gogo"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
send_metrics = false
minify = false

[vars]
UUID = "7384c3a1-1e3d-4a62-ba3e-638d87e8ee42"
PROXYIP = "nima.nscl.ir"

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
